version: "3"

services:

  app:
    image: node:12-stretch
    volumes:
     - .:${WORKDIR:-/var/www/html}
    working_dir: ${WORKDIR:-/var/www/html}
    command: npm run-script run
    ports:
     - ${HTTP_PORT:-8080}:${HTTP_PORT:-8080}
    environment:
     - HTTP_PORT=${HTTP_PORT:-8080}
